image: Ubuntu
configuration: Release

environment:
    Compiler: cygwin
    Arch: x64
 
install:
  ## Download nasm
  - mkdir nasm
  - cd nasm
  - appveyor DownloadFile https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip -FileName nasm.zip
  - 7z e -y nasm.zip
  - set PATH=%PATH%;%CD%
  ## Prepare cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build

  - export "PATH=C:\cygwin64\bin;C:\cygwin64\usr\bin;%PATH%"

before_build:
  - cmake --version

build_script: 
  - cd cmake_build
  - cmake .. -G "Unix Makefiles" -DPNG_SUPPORTED=NO
  - make

artifacts:
- path: cmake_build\**\*.so
- path: cmake_build\**\*.dylib
- path: cmake_build\**\*.dll
- path: cmake_build\**\*.lib
 
