image: Ubuntu
configuration: Release


environment:
    Compiler: cygwin
    Arch: x64
 
install:
  ## Download nasm
  - sudo apt-get install nasm
  ## Prepare cmake
  - cd ${APPVEYOR_BUILD_FOLDER}
  - mkdir cmake_build

before_build:
  - cd cmake_build
  - cmake --version

build_script: 
  - cmake .. -G "Unix Makefiles" -DPNG_SUPPORTED=NO
  - make

artifacts:
- path: cmake_build\**\*.so.0.2.0
