image: Visual Studio 2017
configuration: Release

install:
  ## Download nasm
  - mkdir nasm
  - cd nasm
  - appveyor DownloadFile https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip -FileName nasm.zip
  - 7z e -y nasm.zip
  - set PATH=%PATH%;%CD%
  - cd ..

  ## Download zlib
  - mkdir zlib
  - cd zlib
  - appveyor DownloadFile https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip -FileName zlib.zip
  - 7z e -y zlib.zip
  - set ZLIB=%CD%
  - cd ..

  ## Download libpng
  - mkdir libpng
  - cd libpng
  - appveyor DownloadFile https://downloads.sourceforge.net/project/gnuwin32/libpng/1.2.37/libpng-1.2.37-bin.zip -FileName libpng.zip
  - 7z e -y libpng.zip
  - set PNGLIB=%CD%

  ## Prepare cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build

before_build:
  - cmake --version
  - cd cmake_build
  - cmake .. -G "Visual Studio 15 2017" -ZLIB_LIBRARY="%ZLIB%/bin" -DZLIB_INCLUDE_DIR="%ZLIB%/include" -DPNG_LIBRARY="%PNGLIB%/bin" -DPNG_PNG_INCLUDE_DIR="%PNGLIB%/include"

build_script: 
  - cd %APPVEYOR_BUILD_FOLDER%
  - msbuild cmake_build\mozjpeg.sln

artifacts:
 - path: cmake_build\**\Release\**\*.exe
 - path: cmake_build\**\Release\**\*.dll
 - path: cmake_build\**\Release\**\*.lib
